import { Transaction } from '../types/index.ts';
import { getCurrentMonthKey } from './formatters.ts';

export const generateSampleTransactions = (userId: string, userEmail: string): Omit<Transaction, 'id'>[] => {
  const monthKey = getCurrentMonthKey(); // e.g. 2026-09
  
  return [
    {
      userId,
      userEmail,
      type: 'income',
      amount: 35000,
      category: 'เงินเดือน / ค่าจ้าง',
      date: `${monthKey}-01`,
      paymentMethod: 'transfer',
      note: 'เงินเดือนประจำเดือน',
    },
    {
      userId,
      userEmail,
      type: 'expense',
      amount: 6500,
      category: 'ที่อยู่อาศัยและสาธารณูปโภค',
      date: `${monthKey}-02`,
      paymentMethod: 'transfer',
      note: 'ค่าเช่าห้องและส่วนกลาง',
    },
    {
      userId,
      userEmail,
      type: 'expense',
      amount: 1250,
      category: 'ที่อยู่อาศัยและสาธารณูปโภค',
      date: `${monthKey}-03`,
      paymentMethod: 'transfer',
      note: 'ค่าน้ำ-ค่าไฟ',
    },
    {
      userId,
      userEmail,
      type: 'expense',
      amount: 320,
      category: 'อาหารและเครื่องดื่ม',
      date: `${monthKey}-04`,
      paymentMethod: 'transfer',
      note: 'มื้อกลางวัน + ชานมไข่มุก',
    },
    {
      userId,
      userEmail,
      type: 'expense',
      amount: 140,
      category: 'การเดินทางและยานพาหนะ',
      date: `${monthKey}-05`,
      paymentMethod: 'cash',
      note: 'ค่ารถไฟฟ้า BTS ไป-กลับ',
    },
    {
      userId,
      userEmail,
      type: 'income',
      amount: 4500,
      category: 'งานเสริม / ฟรีแลนซ์',
      date: `${monthKey}-07`,
      paymentMethod: 'transfer',
      note: 'รับออกแบบกราฟิก banner ให้ลูกค้า',
    },
    {
      userId,
      userEmail,
      type: 'expense',
      amount: 890,
      category: 'ช้อปปิ้งและของใช้ส่วนตัว',
      date: `${monthKey}-08`,
      paymentMethod: 'credit',
      note: 'ซื้อของใช้ใน Lotus ซูเปอร์มาร์เก็ต',
    },
    {
      userId,
      userEmail,
      type: 'expense',
      amount: 450,
      category: 'ความบันเทิงและการพักผ่อน',
      date: `${monthKey}-10`,
      paymentMethod: 'credit',
      note: 'ดูหนังรอบค่ำ Major Cineplex',
    },
    {
      userId,
      userEmail,
      type: 'expense',
      amount: 580,
      category: 'อาหารและเครื่องดื่ม',
      date: `${monthKey}-11`,
      paymentMethod: 'transfer',
      note: 'ทานชาบูกับเพื่อนร่วมงาน',
    },
    {
      userId,
      userEmail,
      type: 'expense',
      amount: 250,
      category: 'สุขภาพและการรักษา',
      date: `${monthKey}-12`,
      paymentMethod: 'cash',
      note: 'วิตามินซีและยาประจำบ้าน',
    },
  ];
};
